version: '2.1'
orbs:
  terraform: circleci/terraform@3.2
  docker: circleci/docker@2.6
  aws-cli: circleci/aws-cli@5.1

jobs:
  aws_terraform:
    executor: terraform/default
    working_directory: ./infrastructure/AWS
    steps:
      - checkout
      - run:
          name: List AWS Directory Contents
          command: ls -la ./infrastructure/AWS
      - terraform/fmt
      - terraform/validate
      - terraform/plan
      - terraform/apply

  gcp_terraform:
    executor: terraform/default
    working_directory: ./infrastructure/GCP
    steps:
      - checkout
      - run:
          name: List AWS Directory Contents
          command: ls -la ./infrastructure/GCP
      - aws-cli/setup
      - run:
          name: Retrieve Secret from AWS Secrets Manager
          command: |
            aws secretsmanager get-secret-value --secret-id google_service_account --query SecretString --output text > service_account.json
      - terraform/fmt
      - terraform/validate
      - terraform/plan
      - terraform/apply

workflows:
  deploy_infrastructure:
    jobs:
      # - docker/publish:
      #     image: nidjo13/binance_elt
      #     tag: latest
      #     filters:
      #       branches:
      #         only: main
      - aws_terraform
      - gcp_terraform