version: '2.1'
orbs:
  terraform: circleci/terraform@3.2
  docker: circleci/docker@2.6
  aws-cli: circleci/aws-cli@5.1
jobs:
  aws_terraform:
    executor: terraform/default
    steps:
      - checkout 
      - terraform/fmt
      - terraform/validate
      - terraform/plan
      - terraform/apply
    working_directory: ./AWS/infrastrure
  
  gcp_terraform:
    executor: terraform/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Retrieve Secret from AWS Secrets Manager
          command: |
            aws secretsmanager get-secret-value --secret-id google_service_account --query SecretString --output text > service_account.json
      - terraform/fmt
      - terraform/fmt
      - terraform/validate
      - terraform/plan
      - terraform/apply
    working_directory: ./GCP/infrastrure
workflows:      
  deploy_infrastructure:
    jobs:
      - docker/publish:
          image: nidjo13/binance_elt
          tag: latest
          filters:
            branches:
              only: main
      - aws_terraform
      - gcp_terraform